### ISSUE TITLE
TimeNode 1.1.3 AppImage cannot start

### ISSUE THREAD

**Issue by doctorx32** [chronologic/eth-alarm-clock-dapp#820]
It crashes with:

`dmitry@dmitry-GP60-2PE:~/ethereum/$ ~/Downloads/TimeNode-1.1.3-x86_64.AppImage 

(eth-alarm-clock-dapp:7192): Gtk-WARNING **: 17:22:20.271: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(eth-alarm-clock-dapp:7192): Gtk-WARNING **: 17:22:20.271: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(eth-alarm-clock-dapp:7192): Gtk-WARNING **: 17:22:20.271: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Failed to get 'logs' path
    at Object.<anonymous> (/tmp/.mount_TimeNoP1gFdK/resources/app.asar/main.js:18:25)
    at Object.<anonymous> (/tmp/.mount_TimeNoP1gFdK/resources/app.asar/main.js:270:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Object.<anonymous> (/tmp/.mount_TimeNoP1gFdK/resources/electron.asar/browser/init.js:186:8)
    at Object.<anonymous> (/tmp/.mount_TimeNoP1gFdK/resources/electron.asar/browser/init.js:188:3)
    at Module._compile (module.js:642:30)`

TimeNode 1.1.2 starts normally. Kubuntu 18.04 x64

**Comment by housemobile** [comment]
same issue
